bootstrap_common: &bootstrap_common
  pull: true
  commands:
    - if test "$${FORCED_OS_VERSION}" != ""; then if test "$${FORCED_OS_VERSION}" != "${OS_VERSION}"; then echo "step bypass"; exit 0; fi; fi
    - mkdir -p /opt/metwork-mfext-$${TARGET_BRANCH}
    - ./bootstrap.sh /opt/metwork-mfext-$${TARGET_BRANCH}
    - cat adm/root.mk
    - CACHE_HASH=`./adm2/_build_cache_hash.sh .`
    - if ! test -f /buildcache/build_mfext_$${TARGET_BRANCH}_$${CACHE_HASH}; then echo $${CACHE_HASH} >.drone_cache; fi
  volumes:
    - /buildcache:/buildcache

build_common: &build_common
  commands:
    - if test "$${FORCED_OS_VERSION}" != ""; then if test "$${FORCED_OS_VERSION}" != "${OS_VERSION}"; then echo "step bypass"; exit 0; fi; fi
    - if ! test -f .drone_cache; then echo "build bypass"; exit 0; fi
    - export METWORK_BUILD_OS=${OS_VERSION}
    - mkdir -p /opt/metwork-mfext-$${TARGET_BRANCH}
    - mkdir -p /pub/metwork/continuous_integration/buildlogs/${DRONE_BRANCH}/mfext/${OS_VERSION}/${DRONE_BUILD_NUMBER}
    - make >/pub/metwork/continuous_integration/buildlogs/${DRONE_BRANCH}/mfext/${OS_VERSION}/${DRONE_BUILD_NUMBER}/make.log 2>&1
    - make doc >>/pub/metwork/continuous_integration/buildlogs/${DRONE_BRANCH}/mfext/${OS_VERSION}/${DRONE_BUILD_NUMBER}/make.log 2>&1
    - rm -Rf html_doc
    - cp -Rf /opt/metwork-mfext-$${TARGET_BRANCH}/html_doc .
    - make test >>/pub/metwork/continuous_integration/buildlogs/${DRONE_BRANCH}/mfext/${OS_VERSION}/${DRONE_BUILD_NUMBER}/make.log 2>&1
    - make RELEASE_BUILD=${DRONE_BUILD_NUMBER} rpm >>/pub/metwork/continuous_integration/buildlogs/${DRONE_BRANCH}/mfext/${OS_VERSION}/${DRONE_BUILD_NUMBER}/make.log 2>&1
    - mv /opt/metwork-mfext-$${TARGET_BRANCH}/*.rpm .
  volumes:
    - /pub:/pub
    - /buildcache:/buildcache

publish_ci_common: &publish_ci_common
  commands:
    - if test "$${FORCED_OS_VERSION}" != ""; then if test "$${FORCED_OS_VERSION}" != "${OS_VERSION}"; then echo "step bypass"; exit 0; fi; fi
    - if ! test -f .drone_cache; then echo "publish bypass"; touch .drone_downstream_bypass; exit 0; fi
    - mkdir -p /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    - cp *.rpm /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    - createrepo --update /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}
    - if test "${OS_VERSION}" = "centos6"; then rm -Rf /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfext; mkdir -p /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfext ; cp -Rf html_doc/* /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfext/ ; fi
    - touch /buildcache/build_mfext_$${TARGET_BRANCH}_`cat .drone_cache`
  volumes:
    - /pub:/pub
    - /buildcache:/buildcache

pipeline:
  bootstrap_integration:
    image: metwork/mfext-${OS_VERSION}-buildimage:integration
    environment:
      # yes "master" and not "integration" because we prefer install
      # in the same directory (so we can't install "master" and "integration"
      # at same time) so we can share the cache between integration and
      # master builds (and ci_*, pci_* also)
      - TARGET_BRANCH=master
    <<: *bootstrap_common
    when:
      event: push
      branch: integration
  bootstrap:
    image: metwork/mfext-${OS_VERSION}-buildimage:master
    environment:
      - TARGET_BRANCH=master
    <<: *bootstrap_common
    when:
      event: push
      branch: [ master, ci_*, pci_* ]
  build_integration:
    <<: *build_common
    image: metwork/mfext-${OS_VERSION}-buildimage:integration
    environment:
      - TARGET_BRANCH=master
    when:
      event: push
      branch: integration
  build:
    image: metwork/mfext-${OS_VERSION}-buildimage:master
    environment:
      - TARGET_BRANCH=master
    <<: *build_common
    when:
      event: push
      branch: [ master, ci_*, pci_* ]
  publish_integration:
    <<: *publish_ci_common
    image: metwork/mfext-${OS_VERSION}-buildimage:integration
    environment:
      - TARGET_BRANCH=master
    when:
      event: push
      branch: integration
  publish:
    <<: *publish_ci_common
    image: metwork/mfext-${OS_VERSION}-buildimage:master
    environment:
      - TARGET_BRANCH=master
    when:
      event: push
      branch: [ master, pci_* ]
  trigger:
    image: metwork/drone-downstream-specific-image:${DRONE_BRANCH}
    pull: true
    repositories:
      - metwork-framework/docker-mfcom-${OS_VERSION}-buildimage@${DRONE_BRANCH}
    secrets: [ downstream_token, downstream_server ]
    when:
      status: [ success ]
      event: push
      branch: [ master, integration ]
  trigger_tests:
    image: metwork/drone-downstream-specific-image:${DRONE_BRANCH}
    pull: true
    repositories:
      - metwork-framework/mfext-integration-tests@${DRONE_BRANCH}
    params:
      - FORCED_OS_VERSION=${OS_VERSION}
    secrets: [ downstream_token, downstream_server ]
    when:
      status: [ success ]
      event: push
      branch: [ master, integration ]

matrix:
  OS_VERSION:
    - centos6
    - centos7

branches: [ master, integration, ci_*, pci_* ]
