pipeline:
  build:
    image: metwork/mfext-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    commands:
      - export MODULE=MFEXT
      - export MODULE_LOWERCASE=mfext
      - export RELEASE_BUILD=${DRONE_BUILD_NUMBER}
      - mkdir -p /opt/metwork-mfext-${DRONE_BRANCH}
      - ./bootstrap.sh /opt/metwork-mfext-${DRONE_BRANCH}
      - make
      - make rpm
      - mv /opt/metwork-mfext-${DRONE_BRANCH}/*.rpm .
    volumes:
      - /buildcache:/buildcache
    when:
      event: [push]
  publish_ci:
    image: metwork/mfext-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    commands:
      - mkdir -p /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
      - cp *.rpm /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
      - yum -y install createrepo
      - createrepo --update /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}  
    volumes:
      - /pub:/pub
    when: 
      event: [push]

matrix:
  OS_VERSION:
    - centos6
