pipeline:
  build:
    image: metwork/mfext-${OS_VERSION}-buildimage:master
    commands:
      - export MODULE=MFEXT
      - export MODULE_LOWERCASE=mfext
      - mkdir -p /opt/metwork-mfext
      - ./bootstrap.sh /opt/metwork-mfext
      - make
    volumes:
      - /buildcache:/buildcache

matrix:
  OS_VERSION:
    - centos6
