pipeline:
  build:
    image: metwork/mfext-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    pull: true
    commands:
      - export MODULE=MFEXT
      - export MODULE_LOWERCASE=mfext
      - export RELEASE_BUILD=${DRONE_BUILD_NUMBER}
      - mkdir -p /opt/metwork-mfext-${DRONE_BRANCH}
      - ./bootstrap.sh /opt/metwork-mfext-${DRONE_BRANCH}
      - make
      - make doc
      - rm -Rf html_doc
      - cp -Rf /opt/metwork-mfext-${DRONE_BRANCH}/html_doc .
      - make test
      - make rpm
      - mv /opt/metwork-mfext-${DRONE_BRANCH}/*.rpm .
    volumes:
      - /buildcache:/buildcache
    when:
      event: [push]
  publish_ci:
    image: metwork/mfext-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    commands:
      - mkdir -p /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
      - cp *.rpm /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
      - yum -y install createrepo
      - createrepo --update /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}
      - if test "${OS_VERSION}" = "centos6"; then rm -Rf /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}; mkdir -p /pub/metwork/continuous_integration/docs/${DRONE_BRANCH} ; cp -Rf html_doc/* /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/ ; fi
    volumes:
      - /pub:/pub
    when: 
      event: [push]
  trigger:
    image: plugins/downstream
    fork: true
    repositories:
      - metwork-framework/docker-mfcom-${OS_VERSION}-buildimage@${DRONE_BRANCH}
    secrets: [ downstream_token, downstream_server ]
    when:
      status: [ success ]
      event: push

matrix:
  OS_VERSION:
    - centos6
