pipeline:
  build:
    image: metwork/mfext-${OS_VERSION}-buildimage:master
    commands:
      - env
      - mkdir -p /opt/metwork-mfext
      - ./bootstrap.sh /opt/metwork-mfext

matrix:
  OS_VERSION:
    - centos6
