pull_request_rules:

- name: integration branch
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: false
    delete_head_branch: {}
  conditions:
    - base=integration
    - -merged
    - -closed
    - label!=no-mergify
    - status-success=pr ready to merge
    - status-success=license/cla


