#!/bin/bash

function usage() {
    echo "usage: _layer_hash LAYER_LABEL"
    echo "    => compute (installed) layer hash (without dependencies)"
}

if test "${1}" = ""; then
    usage
    exit 1
fi
if test "${1}" = "--help"; then
    usage
    exit 0
fi
LAYER_LABEL=$1
_layer_dhash "${LAYER_LABEL}" |md5sum |awk '{print $1;}'
