#!/bin/bash

UUID=$(cat "${MFMODULE_RUNTIME_HOME}/var/uuid" 2>/dev/null)
if test "${UUID}" = ""; then
    UUID="unknown"
fi
export UUID

cat "${MFMODULE_HOME}/config/nginx.conf" |envtpl --reduce-multi-blank-lines
