#!/bin/bash

function usage() {
    echo "usage: _doc_layer.sh LAYER_NAME"
}

if test "${1:-}" = ""; then
    usage
    exit 1
fi
if test "${1:-}" = "--help"; then
    usage
    exit 0
fi
export LAYER_NAME=${1}

if test "${LAYER_NAME}" = "root"; then
    touch packages.md
else
    layer_wrapper --layers=python3_devtools@mfext -- "${MFEXT_HOME}/bin/_yaml_to_md.py" "${MODULE_HOME}/opt/${LAYER_NAME}" >packages.md
    if test $? -ne 0; then
        echo "ERROR DURING layer_wrapper --layers=python3_devtools@mfext -- ${MFEXT_HOME}/bin/_yaml_to_md.py ${MODULE_HOME}/opt/${LAYER_NAME}"
        exit 1
    fi
fi

DEPENDENCIES=$(cat .layerapi2_dependencies 2>/dev/null |paste -s -d, -)
CONFLICTS=$(cat .layerapi2_conflicts 2>/dev/null |paste -s -d, -)
LABEL=$(cat .layerapi2_label 2>/dev/null)
EXTRA_ENV=$(cat .layerapi2_extra_env 2>/dev/null)
EXTRA_PROFILE=$(cat .layerapi2_interactive_profile 2>/dev/null)
EXTRA_UNPROFILE=$(cat .layerapi2_interactive_unprofile 2>/dev/null)
UTILITIES=$(cat documented_utilities 2>/dev/null |paste -s -d, -)
export DEPENDENCIES CONFLICTS LABEL EXTRA_ENV EXTRA_PROFILE EXTRA_UNPROFILE UTILITIES
if test "${LAYER_NAME}" = "root"; then
    if test "${UTILITIES}" = ""; then
        export UTILITIES="${MODULE_LOWERCASE}_wrapper"
    else
        export UTILITIES="${MODULE_LOWERCASE}_wrapper,${UTILITIES}"
    fi
    if test "${MODULE}" != "MFEXT" -a "${MODULE}" != "MFCOM"; then
        export UTILITIES="${MODULE_LOWERCASE}.start,${MODULE_LOWERCASE}.stop,${MODULE_LOWERCASE}.status,${MODULE_LOWERCASE}.init,${UTILITIES}"
    fi
fi
export PACKAGES=
if test -s packages.md; then
    export PACKAGES=1
fi

echo
echo "[comment]: # (Generated file from template, DO NOT EDIT THIS FILE DIRECTLY)"
echo

if test -f layer_custom.md; then \
    cat layer_custom.md |envtpl --reduce-multi-blank-lines -i "${MFEXT_HOME}/share/templates,."
    if test $? -ne 0; then
        echo "ERROR during generation"
        exit 1
    fi
else \
    cat "${MFEXT_HOME}/share/templates/layer.md" |envtpl --reduce-multi-blank-lines -i "${MFEXT_HOME}/share/templates,."
    if test $? -ne 0; then
        echo "ERROR during generation"
        exit 1
    fi
fi
rm -f packages.md
