#!/bin/bash

# pip wrapper when you are annoyed with internal https proxies
# WARNING: this is not safe (you can have a man-in-the-middle attack)

if [ -f /etc/redhat-release ];then
    CERT="--cert /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
else
    CERT=""
fi
exec pip $CERT --timeout=60 --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host downloads.sourceforge.net --disable-pip-version-check "$@"
