#!/bin/bash

# pip wrapper when you are annoyed with internal https proxies
# WARNING: this is not safe (you can have a man-in-the-middle attack)

exec pip --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host downloads.sourceforge.net --disable-pip-version-check "$@"
