#!/bin/bash

function usage()
{
    echo "usage: {{MFMODULE_HOME}}/bin/{{MFMODULE_LOWERCASE}}_wrapper COMMAND_TO_WRAP [COMMAND_ARG1] [COMMAND_ARG2] [...]"
    echo "  => launch the given command within metwork/{{MFMODULE_LOWERCASE}} environnent"
    echo "  => note: the current environnent is cleared before"
    echo "  =>       (only MFMODULE_RUNTIME_SUFFIX, MFMODULE_RUNTIME_HOME"
    echo "            and some standard env var (HOME, TERM, DISPLAY...) are keeped intact)"
}

if test "$1" = ""; then
    usage
    exit 1
fi
if test "$1" = "--help"; then
    usage
    exit 0
fi

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CURRENT_BASENAME="$( basename "${0}" )"
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
exec "{{MFEXT_HOME}}/opt/core/bin/layer_wrapper" --empty --empty-env --empty-env-keeps=HOME,TERM,DISPLAY,COLORTERM,HOSTNAME,LANG,LOGNAME,PWD,USER,USERNAME,XAUTHORITY,MFMODULE_RUNTIME_HOME,MFMODULE_RUNTIME_SUFFIX,PATH,LOGPROXY_LOG_DIRECTORY -- bash --noprofile --norc -c "${CURRENT_DIR}/_${CURRENT_BASENAME} $*"
