name: test

on:
  push: {}

env:
    TARGET_DIR: master
    OS_VERSION: centos6
    DOCKER_RUN_OPTIONS: "-v ${{ github.workspace }}:/src -v /buildcache:/buildcache -v /private:/private -v /pub:/pub -e GITHUB_REF -e GITHUB_RUN_NUMBER -e GITHUB_SHA -e TARGET_DIR"
    WORKFLOW_SCRIPTS_DIR: /src/.github/workflows

jobs:
  test:
    runs-on: runner1
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compute reference branch
        id: refrence_branch
        run: |
          TMPREF=${GITHUB_REF#refs/heads/*/}
          echo ::set-output name=name::${TMPREF}
          echo ::set-output name=buildimage::metwork/mfext-${OS_VERSION}-buildimage:integration
      - name: debug env
        run: |
          env
          echo "{{ steps.reference_branch.outputs.name }} = "${{ steps.reference_branch.outputs.name }}
          echo "{{ steps.reference_branch.outputs.buildimage }} = "${{ steps.reference_branch.outputs.buildimage }}
      - name: bootstrap
        run: |
          docker run ${DOCKER_RUN_OPTIONS} --rm ${{ steps.refrence_branch.outputs.buildimage }} /bin/bash -c "${WORKFLOW_SCRIPTS_DIR}/boostrap.sh"
