name: test

on:
  push: {}

jobs:
  test:
    runs-on: self-hosted
    container:
      image: centos:centos6
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: test
        run: |
          pwd
          cat /etc/redhat-release
          find .
